include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/generated/**]
  plugins:
    - custom_lint
  errors:
    # required when using freezed + json_serializable
    # since annotatios are at unexpected places for the analyzer
    invalid_annotation_target: ignore
    # if enabled then there are problems with assigning generated types
    # with freezed to other generated freezed types where both are const
    const_constructor_param_type_mismatch: ignore

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    comment_references: false

